using System;
using System.Collections.Generic;
using Unity.Mathematics;
using UnityEngine;
using UnityEngine.TextCore.Text;
using Yaui.Core;
using Yaui.Layout.Yoga;
using Yaui.Rendering;
using Yaui.Text;

namespace Yaui
{
    /// <summary>
    /// A text element, generated by the Advanced Text Generator (shaping, OS font fallback, line breaking rules
    /// and rich text) and drawn as SDF glyphs by the uber shader. Its size is measured by the layout unless set.
    /// Child elements are ignored.
    /// </summary>
    [AddComponentMenu("YAUI/Text")]
    public class YauiText : YauiElement
    {
        [SerializeField] [TextArea(2, 8)] private string text = "Text";

        /// <summary>The built-in font when null.</summary>
        [SerializeField] private Font font;

        [SerializeField] private float fontSize = 36f;
        [SerializeField] private Color color = Color.black;
        [SerializeField] private TextAlign align = TextAlign.Left;
        [SerializeField] private VerticalAlign verticalAlign = VerticalAlign.Top;
        [SerializeField] private bool wordWrap = true;
        [SerializeField] private bool richText = true;

        /// <summary>The sprites of &lt;sprite&gt; tags (TextCore sprite asset), or none.</summary>
        [SerializeField] private SpriteAsset spriteAsset;

        [SerializeField] private TextOverflow overflow = TextOverflow.Visible;

        /// <summary>
        /// Canvas units around the glyphs, drawn in <see cref="outlineColor"/>. Limited by the distance field of the
        /// font atlas (about a tenth of the font size for dynamic fonts).
        /// </summary>
        [SerializeField] private float outlineWidth;

        [SerializeField] private Color outlineColor = Color.black;

        /// <summary>A copy of the glyphs (and their outline) drawn below them. None without offset or blur.</summary>
        [SerializeField] private Color shadowColor = new(0f, 0f, 0f, 0.5f);

        [SerializeField] private Vector2 shadowOffset;

        /// <summary>Softness of the shadow's edge in canvas units. Limited like <see cref="outlineWidth"/>.</summary>
        [SerializeField] private float shadowBlur;

        private static Font _defaultFont;
        private static readonly List<GlyphQuad> Glyphs = new();

        [NonSerialized] private AtgText _atg;
        [NonSerialized] private FallbackText _fallback;
        [NonSerialized] private int _atgEpoch;

        // The fallback generated at the final width with another size: the next layout must not reuse it.
        [NonSerialized] private bool _forceRelayout;
        [NonSerialized] private Font _fontAssetSource;
        [NonSerialized] private FontAsset _fontAsset;
        [NonSerialized] private YogaMeasureFunc _measure;
        [NonSerialized] private bool _measureDirty;

        // The generation drawn last: its width and its size rounded as measured.
        [NonSerialized] private float _renderedWidth = float.NaN;
        [NonSerialized] private float2 _renderedSize = float.NaN;

        // The size of the text at the final width, before it was elided.
        [NonSerialized] private float2 _naturalSize;

        // Values of the last preparation, to tell layout changes from look changes.
        [NonSerialized] private string _preparedText;
        [NonSerialized] private Font _preparedFont;
        [NonSerialized] private float _preparedFontSize;
        [NonSerialized] private TextAlign _preparedAlign;
        [NonSerialized] private bool _preparedWordWrap;
        [NonSerialized] private bool _preparedRichText;
        [NonSerialized] private SpriteAsset _preparedSpriteAsset;
        [NonSerialized] private TextOverflow _preparedOverflow;

        [NonSerialized] internal bool GenerationDirty;
        [NonSerialized] internal bool GenerationInFlight;
        [NonSerialized] internal bool RenderPending;

        public string Text
        {
            get => text;
            set
            {
                if (text == value) return;

                text = value;
                SyncText();
            }
        }

        public Font Font
        {
            get => font;
            set
            {
                font = value;
                SyncText();
            }
        }

        public float FontSize
        {
            get => fontSize;
            set
            {
                fontSize = value;
                SyncText();
            }
        }

        /// <summary>The default color. Rich text tags can override it.</summary>
        public Color Color
        {
            get => color;
            set
            {
                color = value;
                SyncText();
            }
        }

        public TextAlign Align
        {
            get => align;
            set
            {
                align = value;
                SyncText();
            }
        }

        public VerticalAlign VerticalAlign
        {
            get => verticalAlign;
            set
            {
                verticalAlign = value;
                SyncText();
            }
        }

        public bool WordWrap
        {
            get => wordWrap;
            set
            {
                wordWrap = value;
                SyncText();
            }
        }

        public SpriteAsset SpriteAsset
        {
            get => spriteAsset;
            set
            {
                spriteAsset = value;
                SyncText();
            }
        }

        public bool RichText
        {
            get => richText;
            set
            {
                richText = value;
                SyncText();
            }
        }

        public TextOverflow Overflow
        {
            get => overflow;
            set
            {
                overflow = value;
                SyncText();
            }
        }

        public float OutlineWidth
        {
            get => outlineWidth;
            set
            {
                outlineWidth = value;
                SyncEffects();
            }
        }

        public Color OutlineColor
        {
            get => outlineColor;
            set
            {
                outlineColor = value;
                SyncEffects();
            }
        }

        public Color ShadowColor
        {
            get => shadowColor;
            set
            {
                shadowColor = value;
                SyncEffects();
            }
        }

        public Vector2 ShadowOffset
        {
            get => shadowOffset;
            set
            {
                shadowOffset = value;
                SyncEffects();
            }
        }

        public float ShadowBlur
        {
            get => shadowBlur;
            set
            {
                shadowBlur = value;
                SyncEffects();
            }
        }

        protected override bool AcceptsChildren => false;

        private bool HasShadow => shadowColor.a > 0f && (shadowOffset != Vector2.zero || shadowBlur > 0f);

        private bool HasGeneration => _atg != null ? _atg.IsGenerated : _fallback != null && _fallback.IsGenerated;

        private float GenerationWidth => _atg != null ? _atg.GeneratedWidth : _fallback.GeneratedWidth;

        private float2 GenerationSize => _atg != null ? _atg.Size : _fallback.Size;

        protected override bool HasVisibleContent => !string.IsNullOrEmpty(text);

        private Font EffectiveFont =>
            font != null ? font : _defaultFont ??= Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");

        protected override void OnValidate()
        {
            base.OnValidate();
            SyncText();
        }

        protected override void OnDidApplyAnimationProperties()
        {
            base.OnDidApplyAnimationProperties();
            SyncText();
        }

        protected override void OnRegistered()
        {
            TextPipeline.Register(this);
            SyncText();
        }

        protected override void OnUnregistering()
        {
            TextPipeline.Unregister(this);
            if (GenerationInFlight) TextPipeline.Complete();

            TextPipeline.Forget(this);
            _renderedLength = -1;
            _renderedWidth = float.NaN;
            _renderedSize = float.NaN;
            if (_atg != null) Pools.ReturnText(_atg);

            _atg = null;
            _fallback = null;
            _preparedText = null;
        }

        /// <summary>Queues generation. A change of anything but the look also re-runs the layout.</summary>
        private void SyncText()
        {
            if (NodeSlot <= 0) return;

            if (text != _preparedText || EffectiveFont != _preparedFont || fontSize != _preparedFontSize ||
                align != _preparedAlign || wordWrap != _preparedWordWrap || richText != _preparedRichText ||
                spriteAsset != _preparedSpriteAsset)
            {
                _measureDirty = true;
                Panel.MarkLayoutDirty(this);
            }

            TextPipeline.MarkDirty(this);
            SyncHittable();
            YauiSystem.RequestUpdate();
        }

        /// <summary>The outline and the shadow only change the primitives of the current generation.</summary>
        private void SyncEffects()
        {
            if (NodeSlot <= 0) return;

            TextPipeline.MarkRender(this);
            YauiSystem.RequestUpdate();
        }

        internal override void PrepareLayout()
        {
            // A change of the text only dirties the measurement, not the style.
            base.PrepareLayout();
            var y = Yoga;
            if (!y.HasMeasureFunc) y.SetMeasureFunction(_measure ??= Measure);

            if (_measureDirty)
            {
                _measureDirty = false;
                Panel.AddPendingMeasure(this);
            }
        }

        /// <summary>
        /// Main thread, at scheduling, without ATG: generates with the public generator at the width of the last
        /// drawn generation (or the laid-out width).
        /// </summary>
        internal bool PrepareFallback()
        {
            if (NodeSlot <= 0) return false;

            _atg?.Dispose();
            _atg = null;
            _fallback ??= new FallbackText();
            _fallback.Prepare(text, EffectiveFont, fontSize, color, align, wordWrap, richText);
            _fallback.Generate(float.IsNaN(_renderedWidth) ? ContentWidth() : _renderedWidth);
            _preparedText = text;
            _preparedFont = EffectiveFont;
            _preparedFontSize = fontSize;
            _preparedAlign = align;
            _preparedWordWrap = wordWrap;
            _preparedRichText = richText;
            return true;
        }

        /// <summary>Main thread, at scheduling: prepares the generation. Outputs the width to generate with.</summary>
        internal bool PrepareGeneration(out AtgText generator, out float width)
        {
            generator = null;
            width = -1f;
            if (NodeSlot <= 0 || !AtgText.IsSupported) return false;

            var source = EffectiveFont;
            if (_fontAsset == null || _fontAssetSource != source)
            {
                _fontAsset = AtgText.GetFontAsset(source);
                _fontAssetSource = source;
            }

            if (_fontAsset == null) return false;

            // After a change of font assets the generation info caches stale glyph positions.
            if (_atg != null && _atgEpoch != TextPipeline.FontEpoch)
            {
                _atg.Dispose();
                _atg = null;
            }

            if (_atg == null)
            {
                _atg = Pools.RentText();
                _atgEpoch = TextPipeline.FontEpoch;
            }

            _atg.Prepare((text ?? string.Empty).AsSpan(), new TextRequest
            {
                Font = _fontAsset,
                FontSize = fontSize,
                Color = color,
                Align = align,
                WordWrap = wordWrap,
                RichText = richText,
                Ellipsis = overflow == TextOverflow.Ellipsis,
                SpriteAsset = spriteAsset
            });
            _preparedSpriteAsset = spriteAsset;
            _preparedOverflow = overflow;
            _preparedText = text;
            _preparedFont = EffectiveFont;
            _preparedFontSize = fontSize;
            _preparedAlign = align;
            _preparedWordWrap = wordWrap;
            _preparedRichText = richText;

            // The width of the last drawn generation (valid for the laid-out width) lets the layout job tell if the
            // size changed; before that, the width of the previous layout is the best guess.
            width = float.IsNaN(_renderedWidth) ? ContentWidth() : _renderedWidth;
            generator = _atg;
            return true;
        }

        /// <summary>
        /// Layout thread, after the generation: dirties the layout only if the size changed. The new content was
        /// generated with the width of the last drawn generation, which is valid for the laid-out width; the same
        /// size there means the same size in the layout.
        /// </summary>
        internal void ResolveMeasure()
        {
            var y = Yoga;
            if (!_forceRelayout && HasGeneration && GenerationWidth == _renderedWidth &&
                math.all(math.ceil(GenerationSize) == _renderedSize))
            {
                y.MarkMeasureStale();
            }
            else
            {
                _forceRelayout = false;
                y.MarkDirty();
            }
        }

        /// <summary>
        /// Layout thread: the size of the text within the available space. Regenerates only if the last generation
        /// cannot tell (Yoga node only; no Unity objects).
        /// </summary>
        private YogaSize Measure(YogaNode node, float width, YogaMeasureMode widthMode, float height,
            YogaMeasureMode heightMode)
        {
            if (_fallback != null)
            {
                // The public generator cannot run here: the last generation it is.
                if (!_fallback.IsGenerated) return new YogaSize(0f, 0f);
            }
            else if (_atg == null || !_atg.IsPrepared)
            {
                return new YogaSize(0f, 0f);
            }

            var available = widthMode == YogaMeasureMode.Undefined || float.IsNaN(width) ? -1f : width;
            if (_atg != null && !CanReuse(available, true)) _atg.Generate(available);

            // Rounded up so that pixel grid rounding of the layout never makes the text wrap.
            var size = math.ceil(GenerationSize);
            var w = widthMode switch
            {
                YogaMeasureMode.Exactly => width,
                YogaMeasureMode.AtMost => math.min(size.x, width),
                _ => size.x
            };
            var h = heightMode switch
            {
                YogaMeasureMode.Exactly => height,
                YogaMeasureMode.AtMost => math.min(size.y, height),
                _ => size.y
            };
            return new YogaSize(w, h);
        }

        /// <summary>
        /// Whether the last generation is also the generation at <paramref name="width"/>. With greedy line
        /// breaking, the lines are the same for any width between the longest line and the width generated with.
        /// Other alignments than left also depend on the width itself, unless only the size is needed.
        /// </summary>
        private bool CanReuse(float width, bool sizeOnly)
        {
            // An elided generation is not the size of the text.
            if (!HasGeneration || (_atg != null && _atg.ElidedHeight >= 0f)) return false;

            var generated = GenerationWidth;
            if (generated == width) return true;

            // Without word wrap the lines never depend on the width; only the alignment does.
            if (!_preparedWordWrap) return sizeOnly || _preparedAlign == TextAlign.Left;

            // The prepared values, since this runs on the layout thread while setters may run.
            if (!sizeOnly && _preparedAlign != TextAlign.Left) return false;

            if (width < 0f)
                // Unconstrained: the same only if it was generated unconstrained.
                return generated < 0f;

            return (generated < 0f || generated >= width) && GenerationSize.x <= width;
        }

        private float ContentWidth()
        {
            var y = Yoga;
            var width = y.LayoutWidth - y.LayoutPaddingLeft - y.LayoutPaddingRight - y.LayoutBorderLeft -
                        y.LayoutBorderRight;
            return float.IsNaN(width) || width <= 0f ? -1f : width;
        }

        private float ContentHeight()
        {
            var y = Yoga;
            var height = y.LayoutHeight - y.LayoutPaddingTop - y.LayoutPaddingBottom - y.LayoutBorderTop -
                         y.LayoutBorderBottom;
            return float.IsNaN(height) ? -1f : math.max(height, 0f);
        }

        protected override void OnLayoutApplied()
        {
            TextPipeline.MarkRender(this);
        }

        /// <summary>Main thread, at collection: makes the generation match the final width.</summary>
        internal bool PrepareRender(out AtgText generator)
        {
            generator = null;
            if (_fallback != null)
            {
                if (NodeSlot > 0 && _fallback.IsGenerated && !CanReuse(ContentWidth(), false))
                {
                    var before = _fallback.Size;
                    _fallback.Generate(ContentWidth());
                    if (math.any(before != _fallback.Size))
                    {
                        _forceRelayout = true;
                        _measureDirty = true;
                        Panel.MarkLayoutDirty(this);
                    }
                }

                return false;
            }

            if (NodeSlot <= 0 || _atg == null || !_atg.IsPrepared) return false;

            var width = ContentWidth();
            if (!CanReuse(width, false)) _atg.Generate(width);

            _naturalSize = _atg.Size;
            if (_preparedOverflow == TextOverflow.Ellipsis && width >= 0f)
            {
                // Rounded like the measurement, so that a text that fits is never elided.
                var height = ContentHeight();
                var size = math.ceil(_naturalSize);
                if (height >= 0f && (size.x > width + 0.01f || size.y > height + 0.01f)) _atg.Generate(width, height);
            }

            generator = _atg;
            return true;
        }

        /// <summary>Main thread, at collection: writes the glyphs into primitives in node-local space.</summary>
        internal void WriteGlyphs()
        {
            if (NodeSlot <= 0 || !HasGeneration) return;

            if (_atg != null)
                _atg.Convert(Glyphs);
            else
                _fallback.Convert(Glyphs);

            _renderedWidth = GenerationWidth;
            _renderedSize = math.ceil(_atg != null && _atg.ElidedHeight >= 0f ? _naturalSize : GenerationSize);

            // A shadow is a copy of each glyph (not of sprites), drawn first.
            var shadowed = HasShadow;
            var shadowCount = 0;
            if (shadowed)
                foreach (var g in Glyphs)
                    shadowCount += g.IsSprite ? 0 : 1;

            ResizeContent(Glyphs.Count + shadowCount);

            var y = Yoga;
            var content = new float2(
                y.LayoutWidth - y.LayoutPaddingLeft - y.LayoutPaddingRight - y.LayoutBorderLeft - y.LayoutBorderRight,
                y.LayoutHeight - y.LayoutPaddingTop - y.LayoutPaddingBottom - y.LayoutBorderTop - y.LayoutBorderBottom);
            var origin = new float2(y.LayoutBorderLeft + y.LayoutPaddingLeft, y.LayoutBorderTop + y.LayoutPaddingTop);
            origin.y += verticalAlign switch
            {
                VerticalAlign.Middle => (content.y - GenerationSize.y) * 0.5f,
                VerticalAlign.Bottom => content.y - GenerationSize.y,
                _ => 0f
            };

            // The quads have this much room around the glyphs already.
            var padding = _atg != null ? AtgText.VertexPadding : 0f;
            var outlined = outlineWidth > 0f && outlineColor.a > 0f;
            var outlinePacked = GpuPacking.Color(outlineColor);
            var shadowPacked = GpuPacking.Color(shadowColor);
            var textures = YauiSystem.Textures;
            var written = shadowCount;
            var shadowWritten = 0;
            Texture lastAtlas = null;
            var lastId = 0;
            foreach (var g in Glyphs)
            {
                if (g.Atlas != lastAtlas)
                {
                    lastAtlas = g.Atlas;
                    lastId = textures.GetPermanent(g.Atlas, g.Spread);
                }

                var baseFlags = PrimitiveTexture.With(g.IsSprite ? PrimitiveFlags.Image : PrimitiveFlags.Text, lastId);
                if (g.Bold) baseFlags |= PrimitiveFlags.TextBold;

                var rect = new float4(origin + g.Min, g.Max - g.Min);
                if (g.IsSprite)
                {
                    WriteContent(written++, new PrimitiveData
                    {
                        Rect = rect,
                        UvRect = GpuPacking.Unorm16X4(g.Uv),
                        Color = GpuPacking.Color(g.Color),
                        Flags = baseFlags,
                        BorderWidthAndSkew = GpuPacking.Half2(0f, g.Skew)
                    });
                    continue;
                }

                // How far the distance field of the atlas reaches outside the glyph, in canvas units.
                var uvPerUnit = (g.Uv.zw - g.Uv.xy) / math.max(g.Max - g.Min, 1e-4f);
                var texelsPerUnit = math.abs(uvPerUnit.x) * g.Atlas.width;
                var reach = texelsPerUnit > 0f ? g.Spread / texelsPerUnit * 0.9f : 0f;
                var outline = outlined ? math.min(outlineWidth, reach) : 0f;

                var flags = outline > 0f ? baseFlags | PrimitiveFlags.Border : baseFlags;
                var expanded = Expand(rect, g.Uv, uvPerUnit, g.Skew, outline + 1f - padding);
                WriteContent(written++, new PrimitiveData
                {
                    Rect = expanded.Rect,
                    UvRect = GpuPacking.Unorm16X4(expanded.Uv),
                    Color = GpuPacking.Color(g.Color),
                    BorderColor = outlinePacked,
                    Flags = flags,
                    BorderWidthAndSkew = GpuPacking.Half2(outline, g.Skew)
                });

                if (shadowed)
                {
                    // The shadow dilates like the outline and blurs within what the distance field reaches.
                    var blur = math.clamp(shadowBlur, 0f, math.max((reach - outline) * 2f, 0f));
                    var shadow = Expand(rect, g.Uv, uvPerUnit, g.Skew, outline + blur * 0.5f + 1f - padding);
                    shadow.Rect.xy += (float2)shadowOffset;
                    WriteContent(shadowWritten++, new PrimitiveData
                    {
                        Rect = shadow.Rect,
                        UvRect = GpuPacking.Unorm16X4(shadow.Uv),
                        Color = shadowPacked,
                        Radii = GpuPacking.Half4(new float4(blur, 0f, 0f, 0f)),
                        Flags = baseFlags | PrimitiveFlags.Shadow,
                        BorderWidthAndSkew = GpuPacking.Half2(outline, g.Skew)
                    });
                }
            }

            _glyphOrigin = origin;
            _renderedLength = _preparedText?.Length ?? -1;
            Rendered?.Invoke();
        }

        private struct GlyphRect
        {
            public float4 Rect;
            public float4 Uv;
        }

        /// <summary>
        /// Grows a glyph quad by <paramref name="amount"/> on every side, keeping the mapping to the atlas. The skew
        /// is around the bottom of the rect, so the UVs shift to keep the glyph where it was.
        /// </summary>
        private static GlyphRect Expand(float4 rect, float4 uv, float2 uvPerUnit, float skew, float amount)
        {
            if (amount <= 0f) return new GlyphRect { Rect = rect, Uv = uv };

            var shift = new float2(skew * amount * uvPerUnit.x, 0f);
            return new GlyphRect
            {
                Rect = new float4(rect.xy - amount, rect.zw + amount * 2f),
                Uv = new float4(uv.xy - amount * uvPerUnit + shift, uv.zw + amount * uvPerUnit + shift)
            };
        }

        // Where the glyphs of the last written generation start in the element's box, and the length of its text.
        [NonSerialized] private float2 _glyphOrigin;
        [NonSerialized] private int _renderedLength = -1;

        /// <summary>The length of the text of the last written generation, or -1.</summary>
        internal int RenderedLength => _renderedLength;

        /// <summary>Main thread: the glyphs of a new generation or layout were written.</summary>
        internal event Action Rendered;

        /// <summary>Whether caret and selection queries work: an ATG generation and its selection service.</summary>
        internal bool SupportsSelection => _atg != null && _atg.IsGenerated && AtgSelection.Initialize();

        /// <summary>The height of a line of the font at the font size.</summary>
        internal float LineHeight
        {
            get
            {
                var asset = _fontAsset != null ? _fontAsset : AtgText.GetFontAsset(EffectiveFont);
                if (asset == null || asset.faceInfo.pointSize <= 0f) return fontSize * 1.2f;

                return asset.faceInfo.lineHeight / asset.faceInfo.pointSize * fontSize;
            }
        }

        /// <summary>
        /// The caret before the character at <paramref name="index"/> in the element's box: the top of the caret,
        /// and its height. Needs <see cref="SupportsSelection"/>.
        /// </summary>
        internal void GetCaret(int index, out Vector2 top, out float height)
        {
            var info = _atg.GenerationInfo;
            var bottom = AtgSelection.CursorPosition(info, index);
            height = AtgSelection.CharacterHeight(info, index);
            if (height <= 0f) height = LineHeight;

            top = (Vector2)_glyphOrigin + new Vector2(bottom.x, bottom.y - height);
        }

        /// <summary>The caret index nearest to a point in the element's box.</summary>
        internal int IndexAt(Vector2 local)
        {
            return AtgSelection.IndexFromPosition(_atg.GenerationInfo, local - (Vector2)_glyphOrigin);
        }

        /// <summary>The rectangles that highlight the text between two caret indices, in the element's box.</summary>
        internal Rect[] SelectionRects(int from, int to)
        {
            var rects = AtgSelection.HighlightRectangles(_atg.GenerationInfo, from, to) ?? Array.Empty<Rect>();
            for (var i = 0; i < rects.Length; i++) rects[i].position += (Vector2)_glyphOrigin;

            return rects;
        }

        internal IntPtr SelectionInfo => _atg.GenerationInfo;

    }
}