import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: 'YAUI',
  tagline: 'Yet Another Unity UI: a fast, Flexbox-based UI system on GameObjects.',
  favicon: 'img/favicon.svg',
  url: 'https://ruccho.com',
  baseUrl: '/YAUI/',
  organizationName: 'ruccho',
  projectName: 'YAUI',
  trailingSlash: false,

  onBrokenLinks: 'throw',

  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'ja'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          editUrl: 'https://github.com/ruccho/YAUI/tree/main/docs',
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],
  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        // Generated by docfx and DocFxMarkdownGen (see README.md).
        id: 'api',
        path: 'api',
        routeBasePath: 'api',
        sidebarPath: './sidebars.ts',
      },
    ],
  ],

  themeConfig: {
    image: 'img/hero.png',
    navbar: {
      title: 'YAUI',
      items: [
        {
          type: 'localeDropdown',
          position: 'left',
        },
        {
          to: '/',
          label: 'Docs',
          position: 'left',
          className: 'header-link',
          activeBaseRegex: '^/YAUI/(?!api)',
        },
        {
          to: 'api',
          label: 'API',
          position: 'left',
          className: 'header-link',
        },
        {
          href: 'https://github.com/ruccho/YAUI',
          position: 'right',
          className: 'header-github-link',
          'aria-label': 'GitHub repository',
        },
      ],
      hideOnScroll: true,
    },
    footer: {
      style: 'light',
      copyright: `© ${new Date().getFullYear()} ruccho`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['csharp', 'bash', 'hlsl'],
    },
    colorMode: {
      defaultMode: 'dark',
    },
  } satisfies Preset.ThemeConfig,
  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },
  themes: [
    '@docusaurus/theme-mermaid',
    [
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        language: ['en', 'ja'],
        indexBlog: false,
        docsRouteBasePath: ['/', 'api'],
        docsDir: ['docs', 'api'],
      },
    ],
  ],
};

export default config;
