using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Unity.Mathematics;
using Unity.Profiling;
using UnityEngine;
using UnityEngine.TextCore.Text;
#if UNITY_6000_4_OR_NEWER
using TextAssetId = UnityEngine.EntityId;

#else
using TextAssetId = System.Int32;
#endif

namespace Yaui.Text
{
    internal struct TextRequest
    {
        public FontAsset Font;

        /// <summary>Points; one point is one canvas unit.</summary>
        public float FontSize;

        public Color32 Color;
        public TextAlign Align;
        public bool WordWrap;
        public bool RichText;

        /// <summary>Ends the text with an ellipsis where it overflows the size given to <see cref="AtgText.Generate(float, float)"/>.</summary>
        public bool Ellipsis;

        /// <summary>The sprites of &lt;sprite&gt; tags, or null.</summary>
        public SpriteAsset SpriteAsset;
    }

    /// <summary>A glyph quad relative to the top-left of the text, in canvas units with Y down.</summary>
    internal struct GlyphQuad
    {
        public float2 Min;
        public float2 Max;

        /// <summary>Horizontal offset of the top edge per unit of height (italic).</summary>
        public float Skew;

        /// <summary>xy: UV at <see cref="Min"/>, zw: UV at <see cref="Max"/>.</summary>
        public float4 Uv;

        public Color32 Color;
        public Texture Atlas;

        /// <summary>A sprite of a sprite asset (a color texture) rather than an SDF glyph.</summary>
        public bool IsSprite;

        /// <summary>Distance field spread in texels.</summary>
        public float Spread;

        public bool Bold;
    }

    /// <summary>
    /// Text generated by the Advanced Text Generator, in stages so that the expensive native part can run on
    /// worker threads (planning/poc3-text.md): <see cref="Prepare"/> (main thread), <see cref="Generate"/> (any
    /// thread, may be repeated with other widths), <see cref="ResolveMissingGlyphs"/> (main thread, once for a
    /// batch) and <see cref="Convert"/> (main thread).
    /// </summary>
    internal sealed unsafe class AtgText : IDisposable
    {
        // Canvas units around each glyph quad: enough for anti-aliasing and synthesized bold, without filling
        // much empty atlas area.
        internal const int VertexPadding = 2;

        private static readonly ProfilerMarker GenerateMarker = new("Yaui.Text.Generate");
        private static readonly ProfilerMarker ResolveMissingMarker = new("Yaui.Text.ResolveMissingGlyphs");
        private static readonly ProfilerMarker ConvertMarker = new("Yaui.Text.Convert");

        private static TextSettings _textSettings;

        // Text settings whose default sprite asset is the sprite asset of a text: ATG resolves <sprite> through them.
        private static readonly Dictionary<SpriteAsset, TextSettings> SpriteSettings = new();
        private static object _textInfoList;
        private static readonly List<uint> GlyphBuffer = new();
        private static readonly Dictionary<TextAssetId, HashSet<uint>> AggregatedMissingGlyphs = new();

        private IntPtr _textGenerationInfo;
        private AtgSettings _settings;
        private NativeTextInfo _textInfo;
        private bool _hasMissingGlyphs;

        // ProcessMeshInfos maps the UVs in place, so it must run once per native generation: a cached generation
        // (the same text prepared again, e.g. by OnValidate after an undo) already has atlas UVs.
        private bool _uvsAreGenerated;
        private bool _wordWrap;
        private bool _ellipsis;

        // Pinned so that worker threads can pass it to the native generator.
        private char[] _textBuffer;
        private GCHandle _textBufferHandle;

        private List<List<List<int>>> _textElementIndicesByMesh = new();
        private List<bool> _colorsByMesh;
        private Dictionary<TextAssetId, HashSet<uint>> _missingGlyphs = new();

        /// <summary>Uses the public TextGenerator even if the internal APIs match (tests).</summary>
        internal static bool ForceFallback;

        /// <summary>Whether the internal ATG APIs match this Unity version; otherwise texts use <see cref="FallbackText"/>.</summary>
        public static bool IsSupported => !ForceFallback && AtgInternals.Initialize();

        public AtgText()
        {
            _textGenerationInfo = AtgInternals.CreateGenerationInfo(true);
            EnsureTextBuffer(32);
        }

        /// <summary>The native generation info: <see cref="AtgSelection"/> queries its last generation.</summary>
        public IntPtr GenerationInfo => _textGenerationInfo;

        public bool IsPrepared { get; private set; }

        /// <summary>Whether <see cref="Generate"/> ran since <see cref="Prepare"/>.</summary>
        public bool IsGenerated { get; private set; }

        /// <summary>The width of the last generation, or a negative value if unconstrained.</summary>
        public float GeneratedWidth { get; private set; } = -1f;

        /// <summary>
        /// The height the last generation was elided to, or a negative value if it was not: its size is then not the
        /// size of the text.
        /// </summary>
        public float ElidedHeight { get; private set; } = -1f;

        /// <summary>Size of the last generation.</summary>
        public float2 Size { get; private set; }

        private static TextSettings TextSettings
        {
            get
            {
                if (_textSettings == null)
                {
                    _textSettings = ScriptableObject.CreateInstance<TextSettings>();
                    _textSettings.hideFlags = HideFlags.HideAndDontSave;
                }

                return _textSettings;
            }
        }

        private static TextSettings SettingsFor(SpriteAsset spriteAsset)
        {
            if (spriteAsset == null) return TextSettings;

            if (!SpriteSettings.TryGetValue(spriteAsset, out var settings) || settings == null)
            {
                settings = ScriptableObject.CreateInstance<TextSettings>();
                settings.hideFlags = HideFlags.HideAndDontSave;
                settings.defaultSpriteAsset = spriteAsset;
                SpriteSettings[spriteAsset] = settings;
            }

            return settings;
        }

        /// <summary>Main thread: the dynamic SDF font asset of a font, shared like UI Toolkit does.</summary>
        public static FontAsset GetFontAsset(Font font)
        {
            return IsSupported ? AtgInternals.GetCachedFontAsset(TextSettings, font) : null;
        }

        /// <summary>Main thread: must be called before <see cref="Generate"/> runs on worker threads.</summary>
        public static void PrepareForJobs()
        {
            AtgInternals.CreateHbFaceIfNeeded();
        }

        /// <summary>Main thread: copies the text and builds the native settings, unconstrained in width.</summary>
        public void Prepare(ReadOnlySpan<char> text, in TextRequest request)
        {
            EnsureTextBuffer(text.Length);
            text.CopyTo(_textBuffer);

            var textSettings = SettingsFor(request.SpriteAsset);
            _settings = BuildNativeSettings(request, textSettings);
            _wordWrap = request.WordWrap;
            _ellipsis = request.Ellipsis;
            var usesTextBuffer = AtgInternals.Backend.UsesTextBuffer;
            if (usesTextBuffer)
            {
                _settings.textBufferPtr = _textBufferHandle.AddrOfPinnedObject();
                _settings.textBufferLength = text.Length;
            }
            else
            {
                // Before 6000.6 the text is a string.
                _settings.text = text.ToString();
            }

            if (request.RichText && text.Length > 0) AtgInternals.PreloadAssets(_settings, textSettings);

            if (!usesTextBuffer)
            {
                // Before 6000.6 rich text is parsed here rather than natively: the text loses its tags.
                if (_settings.richTextEnabled && MayHaveTags(text))
                    AtgInternals.Backend.ParseRichText(ref _settings, textSettings);

                _settings.richTextEnabled = false;
            }

            IsPrepared = true;
            IsGenerated = false;
        }

        /// <summary>Any thread: shapes and lays out the text within <paramref name="width"/> (negative: unconstrained).</summary>
        public void Generate(float width)
        {
            Generate(width, -1f);
        }

        /// <summary>
        /// Any thread: like <see cref="Generate(float)"/>, and with <see cref="TextRequest.Ellipsis"/>, ends the text
        /// with an ellipsis where it overflows <paramref name="width"/> and <paramref name="height"/> (not negative).
        /// </summary>
        public void Generate(float width, float height)
        {
            using var _ = GenerateMarker.Auto();
            var constrained = width >= 0f;
            var elide = _ellipsis && constrained && height >= 0f;
            _settings.screenWidth = constrained ? ToFixedPoint(width) : -1;
            _settings.screenHeight = elide ? ToFixedPoint(height) : -1;
            _settings.overflow = elide ? AtgInternals.OverflowEllipsis : AtgInternals.OverflowClip;
            _settings.wordWrapEnabled = _wordWrap && constrained;
            ElidedHeight = elide ? height : -1f;

            var wasCached = false;
            _textInfo = AtgInternals.Backend.GenerateText(AtgInternals.TextLib, _settings, _textGenerationInfo,
                ref wasCached);
            if (!wasCached) _uvsAreGenerated = false;

            Size = new float2(_textInfo.totalWidth / 64f, _textInfo.totalHeight / 64f);
            GeneratedWidth = constrained ? width : -1f;
            IsGenerated = true;

            foreach (var set in _missingGlyphs.Values) set.Clear();

            _hasMissingGlyphs = AtgInternals.HasMissingGlyphs(AtgInternals.TextLib, _textInfo, ref _missingGlyphs);
            if (!_hasMissingGlyphs) ProcessMeshInfos();
        }

        /// <summary>
        /// Main thread: adds the glyphs missing from any of the texts to the atlases (with OS font fallback) once,
        /// then resolves the UVs of those texts. Adding the same glyph twice throws, so they are aggregated.
        /// </summary>
        public static void ResolveMissingGlyphs(List<AtgText> texts)
        {
            if (texts.Count == 0) return;

            using var _ = ResolveMissingMarker.Auto();

            foreach (var set in AggregatedMissingGlyphs.Values) set.Clear();

            // 6000.7 and later resolve OS font fallbacks here; earlier versions have them in the text settings.
            var resolveFallbacks = AtgInternals.ResolveFallbacks != null;
            if (resolveFallbacks)
            {
                _textInfoList ??= AtgInternals.CreateTextInfoList();
                AtgInternals.TextInfoListClear(_textInfoList);
            }

            var anyMissing = false;
            foreach (var text in texts)
            {
                if (!text._hasMissingGlyphs) continue;

                anyMissing = true;
                if (resolveFallbacks) AtgInternals.TextInfoListAdd(_textInfoList, text._textInfo);
                foreach (var pair in text._missingGlyphs)
                {
                    if (pair.Value.Count == 0) continue;

                    if (!AggregatedMissingGlyphs.TryGetValue(pair.Key, out var set))
                        AggregatedMissingGlyphs[pair.Key] = set = new HashSet<uint>();

                    set.UnionWith(pair.Value);
                }
            }

            if (!anyMissing) return;

            if (resolveFallbacks) AtgInternals.ResolveFallbacks(_textInfoList, AggregatedMissingGlyphs);
            foreach (var entry in AggregatedMissingGlyphs)
            {
                if (AtgInternals.FindTextAsset(entry.Key) is not FontAsset fontAsset ||
                    entry.Value.Count == 0) continue;

                GlyphBuffer.Clear();
                GlyphBuffer.AddRange(entry.Value);
                AtgInternals.TryAddGlyphs(fontAsset, GlyphBuffer);
            }

            AtgInternals.CreateHbFaceIfNeeded();
            AtgInternals.UpdateFontAssetsInUpdateQueue();

            foreach (var text in texts)
                if (text._hasMissingGlyphs)
                {
                    text.ProcessMeshInfos();
                    text._hasMissingGlyphs = false;
                }
        }

        private void ProcessMeshInfos()
        {
            foreach (var atlases in _textElementIndicesByMesh)
            foreach (var indices in atlases)
                indices.Clear();

            // Rasterizes newly added glyphs and fills the UVs.
            AtgInternals.Backend.ProcessMeshInfos(AtgInternals.TextLib, _textInfo, _settings,
                ref _textElementIndicesByMesh, ref _colorsByMesh, _uvsAreGenerated);
            _uvsAreGenerated = true;
        }

        /// <summary>Main thread: converts the last generation into glyph quads.</summary>
        public void Convert(List<GlyphQuad> output)
        {
            using var _ = ConvertMarker.Auto();
            output.Clear();

            var meshInfos = (AtgMeshInfo*)_textInfo.m_MeshInfosPtr;
            var ySign = AtgInternals.Backend.FlipsY ? -1f : 1f;
            var processedMeshIndex = 0;
            for (var i = 0; i < _textInfo.meshInfoCount; i++)
            {
                var meshInfo = meshInfos[i];
                var textAsset = AtgInternals.FindTextAsset(meshInfo.textAssetId);
                if (textAsset is SpriteAsset spriteAsset)
                {
                    ConvertSprites(meshInfo, spriteAsset, ySign, output);
                    processedMeshIndex++;
                    continue;
                }

                if (textAsset is not FontAsset fontAsset)
                {
                    if (textAsset != null) processedMeshIndex++;

                    continue;
                }

                var elements = (NativeTextElementInfo*)meshInfo.m_TextElementInfosPtr;
                var spread = IsBitmap(fontAsset) ? 0f : fontAsset.atlasPadding + 1f;
                var atlasIndices = _textElementIndicesByMesh[processedMeshIndex];
                for (var atlasIndex = 0; atlasIndex < atlasIndices.Count; atlasIndex++)
                {
                    // The lists are reused (cleared, not removed): a generation whose font at this mesh had more
                    // atlases leaves empty lists beyond the atlases of this font.
                    if (atlasIndices[atlasIndex].Count == 0) continue;

                    var atlas = fontAsset.atlasTextures[atlasIndex];
                    foreach (var elementIndex in atlasIndices[atlasIndex])
                    {
                        ref var e = ref elements[elementIndex];
                        var glyph = AtgInternals.GetGlyphInCache(fontAsset, (uint)e.glyphID);
                        if (glyph != null && (glyph.metrics.width <= 0f || glyph.metrics.height <= 0f)) continue;

                        // With flipYAxis (6000.7) ATG lays out with Y up from the top-left, so Y is negated.
                        var top = ySign * e.topLeft.position.y;
                        var bottom = ySign * e.bottomLeft.position.y;
                        var left = e.bottomLeft.position.x;
                        var right = e.bottomRight.position.x;
                        output.Add(new GlyphQuad
                        {
                            Min = new float2(left, top),
                            Max = new float2(right, bottom),
                            Skew = bottom > top ? (e.topLeft.position.x - left) / (bottom - top) : 0f,
                            Uv = new float4(e.bottomLeft.uv0.x, e.topRight.uv0.y, e.topRight.uv0.x,
                                e.bottomLeft.uv0.y),
                            Color = e.bottomLeft.color,
                            Atlas = atlas,
                            Spread = spread,
                            Bold = e.bottomLeft.uv2.y != 0
                        });
                    }
                }

                processedMeshIndex++;
            }
        }

        /// <summary>The sprites of &lt;sprite&gt; tags: colored quads of the sprite sheet.</summary>
        private static void ConvertSprites(AtgMeshInfo meshInfo, SpriteAsset spriteAsset, float ySign,
            List<GlyphQuad> output)
        {
            var sheet = spriteAsset.spriteSheet;
            if (sheet == null) return;

            var elements = (NativeTextElementInfo*)meshInfo.m_TextElementInfosPtr;
            for (var i = 0; i < meshInfo.m_TextElementCount; i++)
            {
                ref var e = ref elements[i];
                var top = ySign * e.topLeft.position.y;
                var bottom = ySign * e.bottomLeft.position.y;
                var left = e.bottomLeft.position.x;
                var right = e.bottomRight.position.x;
                if (right <= left || bottom <= top) continue;

                output.Add(new GlyphQuad
                {
                    Min = new float2(left, top),
                    Max = new float2(right, bottom),
                    Skew = (e.topLeft.position.x - left) / (bottom - top),
                    Uv = new float4(e.bottomLeft.uv0.x, e.topRight.uv0.y, e.topRight.uv0.x, e.bottomLeft.uv0.y),
                    Color = e.bottomLeft.color,
                    Atlas = sheet,
                    IsSprite = true
                });
            }
        }

        private void EnsureTextBuffer(int length)
        {
            if (_textBuffer != null && _textBuffer.Length >= length) return;

            if (_textBufferHandle.IsAllocated) _textBufferHandle.Free();

            _textBuffer = new char[Math.Max(length, (_textBuffer?.Length ?? 16) * 2)];
            _textBufferHandle = GCHandle.Alloc(_textBuffer, GCHandleType.Pinned);
        }

        /// <summary>
        /// Whether the atlas of a font asset is a bitmap rather than a distance field: <c>FontAsset.IsBitmap</c>,
        /// public from 6000.7.
        /// </summary>
        private static bool IsBitmap(FontAsset fontAsset)
        {
            // GlyphRasterModes.RASTER_MODE_BITMAP and RASTER_MODE_COLOR.
            const int bitmap = 0x10, color = 0x10000;
            var mode = (int)fontAsset.atlasRenderMode;
            return (mode & bitmap) != 0 && (mode & color) == 0;
        }

        /// <summary>Whether a text may have rich text tags: a '&lt;' followed by a '&gt;'.</summary>
        private static bool MayHaveTags(ReadOnlySpan<char> text)
        {
            var open = text.IndexOf('<');
            return open >= 0 && text[(open + 1)..].IndexOf('>') >= 0;
        }

        private static AtgSettings BuildNativeSettings(in TextRequest request, TextSettings textSettings)
        {
            // The defaults of NativeTextGenerationSettings.
            var s = new AtgSettings { hoveredTag = -1, pixelsPerPointFixed64 = 64 };
            s.fontAsset = AtgInternals.GetNativeFontAsset(request.Font);
            s.textSettings = AtgInternals.GetNativeTextSettings(textSettings);
            s.fontSize = ToFixedPoint(request.FontSize);
            s.color = request.Color;
            s.fontStyle = AtgInternals.FontStyleNormal;
            s.fontWeight = AtgInternals.FontWeightRegular;
            s.horizontalAlignment = request.Align switch
            {
                TextAlign.Center => AtgInternals.HorizontalCenter,
                TextAlign.Right => AtgInternals.HorizontalRight,
                TextAlign.Justified => AtgInternals.HorizontalJustified,
                _ => AtgInternals.HorizontalLeft
            };

            // Vertical alignment is applied by YAUI, since the height is only known after the layout.
            s.verticalAlignment = AtgInternals.VerticalTop;
            s.flipYAxis = true;
            s.screenHeight = -1;
            s.overflow = AtgInternals.OverflowClip;
            s.languageDirection = AtgInternals.LanguageLtr;
            s.richTextEnabled = request.RichText;
            s.vertexPadding = ToFixedPoint(VertexPadding);
            s.pixelsPerPointFixed64 = 64;
            return s;
        }

        private static int ToFixedPoint(float value)
        {
            return (int)(value * 64f);
        }

        public void Dispose()
        {
            if (_textGenerationInfo != IntPtr.Zero)
            {
                AtgInternals.DestroyGenerationInfo(_textGenerationInfo);
                _textGenerationInfo = IntPtr.Zero;
            }

            if (_textBufferHandle.IsAllocated) _textBufferHandle.Free();
        }
    }
}